package co.skyblock.features.nyahirunaddons.na1.partyfinder.utils

import co.skyblock.utils.ListEntryStringColorInt

object TextLines {
    fun getGUIText(
        sbLevel: String?, magicalPower: Int?,
        skillAverage: Double?, cataLevel: Double?,
        archerLevel: Double?, berserkLevel: Double?, mageLevel: Double?, tankLevel: Double?, healerLevel: Double?,
        secrets: Int?, secretAverage: Double?,
        pbF7: String?, pbM4: String?, pbM5: String?, pbM6: String?, pbM7: String?,
        ): List<ListEntryStringColorInt> {
        val texts = listOf(
            ListEntryStringColorInt("§lGeneral", 0xFFCC40FF.toInt()),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > SBLevel $sbLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > Magical Power $magicalPower"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > §nSkill Average $skillAverage"),
            ListEntryStringColorInt(""),

            ListEntryStringColorInt("§lDungeon", 0xFFCC40FF.toInt()),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Cata"),
            ListEntryStringColorInt(" $cataLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Archer", 0xFFDD8800.toInt()),
            ListEntryStringColorInt(" $archerLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Berserk", 0xFFAA0000.toInt()),
            ListEntryStringColorInt(" $berserkLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Mage", 0xFF44CCCC.toInt()),
            ListEntryStringColorInt(" $mageLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Tank", 0xFF00AA00.toInt()),
            ListEntryStringColorInt(" $tankLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Healer", 0xFFFF55FF.toInt()),
            ListEntryStringColorInt(" $healerLevel"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Secrets "),
            ListEntryStringColorInt("$secrets §rper "),
            ListEntryStringColorInt("$secretAverage", 0xFF808000.toInt()),
            ListEntryStringColorInt(""),

            ListEntryStringColorInt("§lPersonal Best S+", 0xFFCC40FF.toInt()),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Floor 7"),
            ListEntryStringColorInt(" [ "),
            ListEntryStringColorInt("$pbF7"),
            ListEntryStringColorInt(" ]"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Master Mode Floor 4"),
            ListEntryStringColorInt(" [ "),
            ListEntryStringColorInt("$pbM4"),
            ListEntryStringColorInt(" ]"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Master Mode Floor 5"),
            ListEntryStringColorInt(" [ "),
            ListEntryStringColorInt("$pbM5"),
            ListEntryStringColorInt(" ]"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Master Mode Floor 6"),
            ListEntryStringColorInt(" [ "),
            ListEntryStringColorInt("$pbM6"),
            ListEntryStringColorInt(" ]"),
            ListEntryStringColorInt("\n"),
            ListEntryStringColorInt(" > "),
            ListEntryStringColorInt("Master Mode Floor 7"),
            ListEntryStringColorInt(" [ "),
            ListEntryStringColorInt("$pbM7"),
            ListEntryStringColorInt(" ]")
        )

        return texts
    }
}